### PR TITLE
Updated with new Sky-Q Skin

### PR DESCRIPTION
**Pull request by DJBenson**
I've added a new Sky-Q skin (accessed by adding /skyq.html to the URL). I'm going to try and merge them into a single page at some point so appending the URL isn't necessary.

### CODE REVIEW

**Comment by dalhundal** [comment]
Thanks for contributing @DJBenson :)

The SkyQ remote skin looks good, it doesn't actually control a SkyQ box though.

It just needs to let the server know that its a SkyQ box its controlling, so it can pass in the right port when creating the SkyRemote object.

`var remoteControl = new SkyRemote('192.168.0.40', SkyRemote.SKY_Q);`

I'll have a look at this in the next day or so, or if you can fix it that'd be great too.

**Comment by DJBenson** [comment]
I can see my mistake here; I made a local edit to `sky-remote-web.js` (as you showed above) but I did not contribute that file back as it would have switched from working only with SkyHD to SkyQ. 

Not sure how to work around that one.

I can however confirm that it works with both my SkyQ Silver (2TB) box and also my SkyQ Mini's.

**Comment by pechula** [comment]
Hi guys
Please can anyone explain what do I do with this to make it work. I have no idea even on where or how to start, or is it too complicated?

**Comment by jameslumgair** [comment]
z

**Pull request closed without merging**
